
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("POSTGRES_USER")  %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  database: appagar_<%= ENV.fetch("RAILS_ENV") %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default

